
# https://circleci.com/docs/ja/2.0/language-javascript/


# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

# Environment valuse
# ENV : base64 encoded .env file

version: 2
jobs:
  build:
    # branches:
    #   only:
    #     - master
    docker:
      # specify the version you desire here
      - image: circleci/node:10.13.0 #node:7.10 #https://circleci.com/docs/2.0/docker-image-tags.json

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn build
      - run:
          name: Decode dotenv file
          command: |
            echo $ENV | base64 --decode > .env
            pwd
            cat .env
      # - deploy:
      #     name: deployment
      #     command: |
      #       ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
      #       sudo apt install -y rsync
      #       ssh ${USER_NAME}@${HOST_NAME} "service ${APP_NAME} stop" # サービスを停止する
      #       rsync -vc ${BUILD_APP} ${USER_NAME}@${HOST_NAME}:${APP_DIR} # 成果物をデプロイする
      #       ssh ${USER_NAME}@${HOST_NAME} "service ${APP_NAME} start" # サービスを起動する
