/** Declaration file generated by dts-gen
 *
 * > dts-gen -m emoji
*/

export const EMOJI_MAP: string[][];

export function EMOJI_DOCOMO_RE(): any;

export function EMOJI_GOOGLE_RE(): any;

export function EMOJI_KDDI_RE(): any;

export function EMOJI_RE(): any;

export function EMOJI_SOFTBANK_RE(): any;

export function docomoToUnified(text: any): any;

export function googleToUnified(text: any): any;

export function kddiToUnified(text: any): any;

export function softbankToUnified(text: any): any;

export function unifiedToHTML(text: any): any;

